[package]
name = "coderd"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
clap.workspace = true
coder-audit = { path = "../../crates/coder-audit" }
coder-connectivity = { path = "../../crates/coder-connectivity" }
coder-core = { path = "../../crates/coder-core" }
coder-db = { path = "../../crates/coder-db" }
coder-rbac = { path = "../../crates/coder-rbac" }
coder-server = { path = "../../crates/coder-server" }
metrics-exporter-prometheus.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
