[package]
name = "coder-rbac"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
coder-core = { path = "../coder-core" }
serde.workspace = true
uuid.workspace = true
