[package]
name = "coder-notifications"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
coder-core = { path = "../coder-core" }
lettre.workspace = true
p256.workspace = true
rand.workspace = true
reqwest.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
web-push.workspace = true

[dev-dependencies]
async-trait.workspace = true
