[package]
name = "coder-provisioner"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
sha2.workspace = true
thiserror.workspace = true
