-- Enums for the notifications domain.
-- Wrapped in DO blocks for idempotency (enum_types migration may have
-- already created these types).

DO $$ BEGIN
    CREATE TYPE notification_message_status AS ENUM (
        'pending',
        'leased',
        'sent',
        'permanent_failure',
        'temporary_failure'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE notification_method AS ENUM (
        'smtp',
        'webhook',
        'inbox'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE notification_template_kind AS ENUM (
        'system',
        'custom'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE inbox_notification_read_status AS ENUM (
        'all',
        'unread',
        'read'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- notification_templates: Templates from which to create notification messages.
CREATE TABLE notification_templates (
    id          UUID NOT NULL PRIMARY KEY,
    name        TEXT NOT NULL,
    title_template TEXT NOT NULL,
    body_template  TEXT NOT NULL,
    actions     JSONB,
    "group"     TEXT,
    method      notification_method,
    kind        notification_template_kind NOT NULL DEFAULT 'system'::notification_template_kind,
    enabled_by_default BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE notification_templates IS 'Templates from which to create notification messages.';
COMMENT ON COLUMN notification_templates.method IS 'NULL defers to the deployment-level method';

-- notification_messages: Queued notification messages.
CREATE TABLE notification_messages (
    id                       UUID NOT NULL PRIMARY KEY,
    notification_template_id UUID NOT NULL REFERENCES notification_templates (id),
    user_id                  UUID NOT NULL REFERENCES users (id),
    method                   notification_method NOT NULL,
    status                   notification_message_status NOT NULL DEFAULT 'pending'::notification_message_status,
    status_reason            TEXT,
    created_by               TEXT NOT NULL,
    payload                  JSONB NOT NULL,
    attempt_count            INTEGER DEFAULT 0,
    targets                  UUID[] NOT NULL DEFAULT '{}',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ,
    leased_until             TIMESTAMPTZ,
    next_retry_after         TIMESTAMPTZ,
    queued_seconds           DOUBLE PRECISION,
    dedupe_hash              TEXT
);

COMMENT ON COLUMN notification_messages.dedupe_hash IS 'Auto-generated by insert/update trigger, used to prevent duplicate notifications from being enqueued on the same day';

-- notification_preferences: Per-user notification template preferences.
CREATE TABLE notification_preferences (
    user_id                  UUID NOT NULL REFERENCES users (id),
    notification_template_id UUID NOT NULL REFERENCES notification_templates (id),
    disabled                 BOOLEAN NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, notification_template_id)
);

-- notification_report_generator_logs: Log of generated reports for users.
CREATE TABLE notification_report_generator_logs (
    notification_template_id UUID NOT NULL PRIMARY KEY REFERENCES notification_templates (id),
    last_generated_at        TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE notification_report_generator_logs IS 'Log of generated reports for users.';

-- inbox_notifications: In-app inbox notifications.
CREATE TABLE inbox_notifications (
    id          UUID NOT NULL PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users (id),
    template_id UUID NOT NULL REFERENCES notification_templates (id),
    targets     UUID[] NOT NULL DEFAULT '{}',
    title       TEXT NOT NULL,
    content     TEXT NOT NULL,
    icon        TEXT NOT NULL,
    actions     JSONB NOT NULL,
    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- webpush_subscriptions: Web push notification subscriptions.
CREATE TABLE webpush_subscriptions (
    id                  UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES users (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endpoint            TEXT NOT NULL,
    endpoint_p256dh_key TEXT NOT NULL,
    endpoint_auth_key   TEXT NOT NULL,
    UNIQUE (user_id, endpoint)
);
